name: Start Actions
on: workflow_dispatch

jobs:
  linux:
    name: Building recovery for samsung M01 core
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: downloading recovery
      run: wget https://cdn-126.anonfiles.com/jfVcU1Vex2/0883086f-1649755819/recovery.img.lz4

    - name: building new recovery
      run: sh ./run.sh
